src/main/resources/application.yaml:
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: order_user
    password: order_pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oauth2-car-realm

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

grpc:
  client:
    storage-service:
      address: static://localhost:9090
      negotiation-type: plaintext

server:
  port: 8081